docs: Add Docker Compose Setup for ServerlessLLM
ServerlessLLM/ServerlessLLM pull request #137
Opened 2024-11-03 21:57 UTC by future-xy

## Description
This PR introduces a Docker Compose setup to simplify the startup process:
- Added a `docker-compose.yml` file.
- Updated the Docker quick start guide with new instructions for using Docker Compose.

## Motivation
This update makes it easier to launch a ServerlessLLM cluster on a local GPU machine for development and testing. It also completes a roadmap item outlined in #113.

## Type of Change
- [x] Documentation update

## Checklist
- [x] I have read the [CONTRIBUTION](https://github.com/ServerlessLLM/ServerlessLLM/blob/main/CONTRIBUTING.md) guide.
- [x] I have updated the documentation (if applicable).

2024-11-04 06:07 UTC, SiyangShao requested changes

2024-11-04 06:07 UTC, SiyangShao commented on docs/stable/getting_started/docker_quickstart.md
> +We will use docker-compose to simplify the setup of ServerlessLLM. The `docker-compose.yml` file is located in the `examples/docker_compose/` directory of the ServerlessLLM repository.
Currently it's under `examples/docker_cluster/` directory.

2024-11-04 06:07 UTC, SiyangShao commented on docs/stable/getting_started/docker_quickstart.md
> +cd serverlessllm/examples/docker_compose/
Same, now it's under `examples/docker_cluster`

2024-11-04 06:07 UTC, SiyangShao commented on docs/stable/getting_started/docker_quickstart.md
> +docker-compose up -d --build
Seems that in current version, it should be `docker compose` compared with `docker-compose`? ref: https://docs.docker.com/compose/releases/migrate/

2024-11-04 06:07 UTC, SiyangShao commented on docs/stable/getting_started/docker_quickstart.md
> +docker-compose down
Same. `docker compose down` may be better.

2024-11-04 11:05 UTC, JustinTong0323 commented
As the default mem_pool_size for sllm-store-server is 4, which is relative small and difficult to handle large model, I think there maybe need a option for adjusting it when using docker to deploy the sllm.

2024-11-05 23:53 UTC, future-xy commented
> As the default mem_pool_size for sllm-store-server is 4, which is relative small and difficult to handle large model, I think there maybe need a option for adjusting it when using docker to deploy the sllm.

sounds good, will fix later

2024-11-06 01:37 UTC, SiyangShao approved these changes
LGTM. BTW, will the configuration for mem_pool_size be in another PR or in this PR?

2024-11-06 12:05 UTC, future-xy commented
> LGTM. BTW, will the configuration for mem_pool_size be in another PR or in this PR?

It will be in a separate PR, as it involves modifying the entrypoint and requires additional testing.

2024-11-06 12:06 UTC, merged