#Issue 116
ServerlessLLM/ServerlessLLM pull request #145
Opened 2024-11-09 11:08 UTC by dalongbao

## Description
Github Action that will start the sllm server via `entrypoint.sh` attempt to store every model in the list of supported models, then run inference on them. Prints which models fail the tests.

Future improvements:
* Model batching (in case storage runs out) 
* Improve how `supported_models.json` is updated

## Motivation
`close #116`

## Type of Change
- [ ] Bug fix
- [X] New feature
- [ ] Breaking change
- [ ] Documentation update

## Checklist
- [X] I have read the [CONTRIBUTION](https://github.com/ServerlessLLM/ServerlessLLM/blob/main/CONTRIBUTING.md) guide.
- [X] I have updated the tests (if applicable).
- [X] I have updated the documentation (if applicable).

2024-11-11 14:01 UTC, future-xy requested changes
Thank you for your hard work on this PR! This is a fantastic start, and the quality is impressive—it’s clear you’ve put a lot of effort into it. I’ve added a few comments with best practice suggestions to make it even stronger. Please feel free to reach out here if anything is unclear—I’m here to help!

**Tips**: There are a couple of ways to test GitHub Actions locally:

1. You can emulate the steps by starting a Docker environment with the same image specified in your YAML file, then manually replay each step.
2. Alternatively, you can use a tool called [`act`](https://github.com/nektos/act), which enables you to run entire workflows locally.

Thanks again, and let me know if you have any questions!

2024-11-13 23:54 UTC, dalongbao commented
Addressed all the comments

2024-11-14 14:13 UTC, future-xy commented
Thank you for the updates! 

A few points to address before merging:

1. **Testing the Workflow**: Have you run the workflow locally using `act`? It seems there are still some issues to resolve:
   - There’s a format error on the first line of `inference_test.yml` (see screenshot).
   - The checkpoint store doesn’t seem to launch within the workflow, which could lead to issues in testing.
   - The `sllm` workers may also need verification, as they don’t appear to be properly initialized.

<img width="878" alt="image" src="https://github.com/user-attachments/assets/d81ea7fc-cce7-48ff-8a09-05ad99911f9c">

2. **Naming and Formatting**: Could you rename the PR to better reflect the changes and run `pre-commit` to format your code? You can refer to our [contributing guide](https://github.com/ServerlessLLM/ServerlessLLM/blob/main/CONTRIBUTING.md) for more guidance.

Let me know if you'd like any help using `act` for local testing—I can also add instructions in the contributing guide if helpful! Thanks again for your work on this.

2024-11-14 14:15 UTC, future-xy commented
BTW, the VSCode extension "GitHub Actions" can also help with editing and validating workflow files.

2024-11-19 14:50 UTC, future-xy requested changes

2024-11-19 14:50 UTC, future-xy commented on .github/workflows/inference_test.yml
> +      - name: Test sllm store
In the previous step, when starting the entrypoint in "HEAD" mode, the `sllm-store-server` is not started, so this test should not have a chance to pass.

2024-11-19 14:50 UTC, future-xy commented on .github/workflows/inference_test.yml
> +          pip install ray vllm
I would expect the two commands above to install dependencies like ray and vllm, wouldn’t they? If they don’t, that seems like a bug.

2024-11-19 14:50 UTC, future-xy commented on docs/stable/models/supported_models.md
> +Architecture      |Models        |Example HF Models   |vLLM |Transformers |ONNX |TensorRT
Let’s remove ONNX and TensorRT. It’s probably not a good idea to mention frameworks that are unsupported (not even partially supported) here.

2024-11-22 10:26 UTC, future-xy reviewed
Looks good to me. I’ll approve and merge once all tests pass.

2024-11-22 22:48 UTC, future-xy approved these changes

2024-11-22 22:49 UTC, merged