Fy/new entrypoint
ServerlessLLM/ServerlessLLM pull request #147
Opened 2024-11-09 16:30 UTC by future-xy

## Description

This PR includes two main changes:
1. Updated Docker entrypoint scripts and `docker-compose.yml` to allow passing custom startup arguments to `sllm-serve` and `sllm-store-server`, enabling configuration flexibility (e.g., setting memory pool size).
2. Enhanced the README with instructions on customizing the Docker Compose setup, including an example for memory pool configuration.

## Motivation

These changes address the need for more flexible runtime configuration options (discussed during #137), allowing users to easily adjust startup settings for `sllm-serve` and `sllm-store-server` without modifying the underlying code. This is particularly useful for tuning deployments to specific resource constraints. The README update also improves usability by providing clear, practical guidance on configuring Docker Compose.

Fixes #141.

## Type of Change

- [x] Bug fix
- [x] Documentation update

## Checklist

- [x] I have read the [CONTRIBUTION](https://github.com/ServerlessLLM/ServerlessLLM/blob/main/CONTRIBUTING.md) guide.
- [ ] I have updated the tests (if applicable).
- [x] I have updated the documentation (if applicable).

2024-11-11 09:24 UTC, JustinTong0323 requested changes

2024-11-11 09:24 UTC, JustinTong0323 commented on entrypoint.sh
If we use `$@` to pass the args, put it after both `sllm_serve` and `sllm_store_server` would cause conflicts. As if we run `./entrypoint.sh mem_pool_size=32` this would also pass to `sllm_serve` and get error.

2024-11-11 21:04 UTC, JustinTong0323 commented on entrypoint.sh
Yes that's correct, sorry for the confusion.

2024-11-12 01:04 UTC, JustinTong0323 approved these changes
LGTM

2024-11-12 01:27 UTC, SiyangShao approved these changes

2024-11-12 08:23 UTC, merged