draft: support lora fine-tuning for SLLM
ServerlessLLM/ServerlessLLM pull request #189
Opened 2024-12-29 13:49 UTC by MartinRepo

## Description
Briefly describe your changes.

## Motivation
Explain why this change is needed and what problem it solves.
If it fixes an issue, link it (e.g., `close #123`).

## Type of Change
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation update

## Checklist
- [ ] I have read the [CONTRIBUTION](https://github.com/ServerlessLLM/ServerlessLLM/blob/main/CONTRIBUTING.md) guide.
- [ ] I have updated the tests (if applicable).
- [ ] I have updated the documentation (if applicable).

2025-01-24 22:20 UTC, future-xy commented
Thank you, @MartinRepo! 

@XuehengWang and @SiyangShao, could you please review this PR? Since this is @MartinRepo's first code contribution, let's work together to help him get the code ready. Thanks!

2025-01-26 22:29 UTC, XuehengWang commented on sllm/serve/backends/transformers_backend.py
> +        self.inf_status.delete()
Do we need this `delete` here, since the streamer is not used during fine tuning?

2025-01-26 22:45 UTC, XuehengWang commented on sllm/serve/backends/transformers_backend.py
> +        train_sample = train_sample.remove_columns("act")
Could you separate the dataset loading logic? I think it would allow users to more easily customize how the training data is processed.

2025-01-26 22:46 UTC, XuehengWang commented on sllm/serve/backends/transformers_backend.py
> +        train_sample = train_sample.remove_columns("act")
Also, it would be great to add some validation for the provided fields (e.g., dataset path, model name, LoRA config).

2025-01-26 22:53 UTC, XuehengWang reviewed
The new feature looks good! I've added a few comments suggesting some improvements.

2025-01-26 22:53 UTC, MartinRepo commented on sllm/serve/backends/transformers_backend.py
> +        self.inf_status.delete()
Sure. Sorry about that. We don't need it, inf_status is for inference.

2025-01-27 05:45 UTC, SiyangShao commented
Could you also update the document (under `docs/stable/cli/cli_api.md`) and examples about how to use the fine-tune functions?

2025-01-27 06:06 UTC, SiyangShao requested changes

2025-01-27 06:06 UTC, SiyangShao commented on sllm/serve/backends/transformers_backend.py
> +        foundation_model = AutoModelForCausalLM.from_pretrained(base_model_name)
Since when we init the transformer backend, we already init a model (`self.model`) via `sllm_store`. But it seems that here we are trying to load a new model. Can we use the previously loaded model as the foundation model?

2025-01-27 06:06 UTC, SiyangShao commented on sllm/serve/backends/transformers_backend.py
General question about `transformers backend`:

It seems that the fine-tuning part is quite independent (does not reuse the model loaded) and looks like a more compute-costly model downloader part. What's the main reason we put the fine-tune function as a service similar to generation, compared with a new function like `lora-fintuner` similar to model downloader?

2025-01-27 09:30 UTC, XuehengWang commented on sllm/serve/backends/transformers_backend.py
I agree that we can separate fine_tuning with generate/encode, given the workloads are different and it reloads another base model.

2025-01-27 09:54 UTC, XuehengWang commented on sllm/serve/backends/transformers_backend.py
> +        train_sample = train_sample.remove_columns("act")
I think putting the dataset in file `default_ft_config.json` would be fine, and use a separate function for preprocessing the provided dataset.

2025-01-27 09:56 UTC, MartinRepo commented on sllm/serve/backends/transformers_backend.py
> +        train_sample = train_sample.remove_columns("act")
This is just a sample for development testing. What about adding a field "dataset_config" in ``default_ft_config.json`` like:
```
{
...,
"dataset_config": {
"is_from_local": ,
"file_extension_type": ,
"data_files": 
},
...,
}
```
The parameters here can be consistent with those required by [load_dataset()] (https://huggingface.co/docs/datasets/en/loading#local-and-remote-files)

2025-01-27 10:32 UTC, MartinRepo commented on sllm/serve/backends/transformers_backend.py
> +        foundation_model = AutoModelForCausalLM.from_pretrained(base_model_name)
Yes, we can reuse the previously loaded model.

2025-01-27 22:40 UTC, XuehengWang commented on sllm/serve/backends/transformers_backend.py
> +        train_sample = train_sample.remove_columns("act")
sure, then the dataset loading logic can be implemented based on file types

2025-01-27 23:26 UTC, MartinRepo commented on sllm/cli/default_ft_config.json
> +    "model": "",
Because the function `inference_handler` in `sllm/serve/app_lib.py` will check the model_name firstly. For `ray.get_actor()`

2025-01-31 10:00 UTC, MartinRepo commented on sllm/serve/backends/transformers_backend.py
> +        with self.status_lock:
I'm not quite sure of the logic behind the blocking. In other words, what happens if we go ahead and receive other requests without blocking the model?

2025-01-31 10:14 UTC, MartinRepo commented
Hi Both @SiyangShao @XuehengWang. Many thanks for your review and valuable suggestions!

I've made the following changes:
1. we do not need inf_status.delete() in the fine-tuning function, so delete it.
2. default_ft_config.json has been modified. It now consists of three parts, `dataset_config`, `lora_config`, and `training_config`
3. I have added some validation for the provided fields (`dataset_config`, `lora_config`, `training_config`, etc.)
4. A new function `_load_dataset(self, dataset_config, tokenizer)` added for loading dataset based on the configuration.
5. Document (under docs/stable/cli/cli_api.md) and examples have been updated.

Just let me know if there are any other changes that need to be made. Many thanks again! :)

2025-02-01 12:34 UTC, future-xy commented
@JustinTong0323 Please have a look since this pr also modified `cli`

2025-02-03 00:09 UTC, JustinTong0323 requested changes

2025-02-03 00:09 UTC, JustinTong0323 commented on sllm/cli/fine_tuning.py
Could you please add some basic validations for ft config?

2025-02-03 15:00 UTC, MartinRepo commented on sllm/cli/fine_tuning.py
Sure, I have added the `validate_config()` function in `sllm/cli/fine-tuning.py`, to validate some basic fields like `model` and `dataset_source`. Other fields, like `training_config` and `lora_config`, are validated uniformly in `sllm/serve/backends/transformers_backend.py`.

2025-02-04 22:38 UTC, JustinTong0323 approved these changes

2025-02-09 14:22 UTC, MartinRepo commented on sllm/serve/backends/transformers_backend.py
> +        with self.status_lock:
Sorry, I misunderstood you before. So what I need to do is to introduce a new status lock (`ft_status_lock`) to manage the status of the fine-tuning process separately?

Apart from that, do I need to invoke `threading.Thread()` to have the fine-tuning run in a separate thread, which allows fine-tuning and generate/encode to run concurrently?

2025-02-10 02:52 UTC, SiyangShao commented on sllm/serve/backends/transformers_backend.py
> +        with self.status_lock:
Currently, we only check the status is running or not, and accept the fine-tuning if the status is running. However, what will happen if there are two fine-tuning process routed to the same server? Will that introduce any problems? Also, I'm not sure whether fine-tunning and inference on the same instance is better or not.

From my perspective, I think we do not need to create a new thread. I prefer to label the status as "fine-tunning" or sth similar so that inference requests and other fine-tune requests will not be routed to this instance.

Also, if we change the code into such a logic, please make sure that our autoscaler will still works.

2025-02-10 10:55 UTC, future-xy commented on sllm/serve/backends/transformers_backend.py
> +        with self.status_lock:
This issue has been around for a while. @XuehengWang also noted that the Transformers backend doesn't actually limit the number of concurrent inference requests—the previous solution was to enforce this in the router logic.  

I haven't seen any other library or framework supporting fine-tuning and inference simultaneously in the same backend. Serverless fine-tuning itself is a relatively new concept, so we should discuss this further.  

My initial proposal is that, for now, when a backend is performing fine-tuning, it shouldn't handle inference requests, and vice versa. And the best way to enfoorce this limit seems to be in the router instead of backend. What do you think?

2025-02-10 11:42 UTC, MartinRepo commented on sllm/serve/backends/transformers_backend.py
> +        with self.status_lock:
Sounds good! It would also make the whole structure more clear. Because fine-tuning is a kind of training process, not the inference process. And the way I currently write it is to integrate fine-tuning into inference (which doesn't make sense).

I will write a new function `fine_tuning` in the router, distinct from `inference`, to make the two cannot go together. And give `fine_tuning` a separate counter and state lock (`self.fine_tuning_count`, similar to `self.request_count`). Additionally, this way, instead of adding `fine_tuning` to the `inference_handler()` in `sllm/serve/app_lib.py` (which is logically a bit strange), I can just use `fine_tuning_handler()` instead.

2025-02-12 19:55 UTC, MartinRepo commented
Hello guys @future-xy @SiyangShao @XuehengWang . Thank you all so much for your patience and guidance! I think I've now isolated the `fine_tuning` process and the `inference` process. After testing, the fine-tuning feature is working well and I hope to get your suggestions again!

2025-02-17 08:24 UTC, SiyangShao requested changes
I've checked the current logic. In general, it's quite good but I still have some concerns about the router logic.

Currently, `fine_tuning` requests and `inference` requests will share the same scaling threshold in autoscaler (in line 265 of `roundrobin_router.py`) and same instance request length checking logic (in line 246). However, I think they should be somehow different. If it's inference request, let's keep the current logic in both autoscaling and routing. But if it's fine-tunning request, I think in any case, it should be one request occupy a whole instance, no matter how user write in the config files. How do you think @future-xy ?

Another point is currently one kind of model could only serve one kind of request. If there's inference requests in processing, fine-tune requests will be rejected. However, I don't think it should have a such hard limit. It would be fine if there's some inference instances processing inference tasks and some fine-tuning instances processing fine-tunning tasks. But considering it may be little bit tricky to do such a change, it's also fine if we keep the current logic and do the modification in future updates.

2025-02-17 08:24 UTC, SiyangShao commented on sllm/serve/routers/roundrobin_router.py
> +    async def fine_tuning(self, request_data: dict):
Please also modify `router_utils.py` and claim that fine_tuning is only applicable on roundrobin router

2025-02-17 08:24 UTC, SiyangShao commented on sllm/serve/routers/roundrobin_router.py
> +        instance_id = await instance_allocation
Need to notice that `instance_allocation` could route multiple requests to same instance if number of requests does not exceed the limit in config (see `_load_balancer_loop` function). I don't think multiple fine-tunning tasks could be routed to the same instance. So use the same threshold may not be a good idea.

2025-02-17 08:50 UTC, MartinRepo commented on docs/stable/cli/cli_api.md
> +    "model": "bigscience/bloomz-560m",
Yes, this is the base model

2025-02-17 08:56 UTC, MartinRepo commented on sllm/cli/fine_tuning.py
> +        self.base_model = args.base_model
I think we need it, because some logger messages will mention this, such as `logger.info(f"Start fine-tuning base model {self.base_model}")` and `logger.info(f"{self.base_model} fine-tuned successful.")`. Otherwise, I can delete this arg, and get model name from the config file.

2025-02-17 09:46 UTC, MartinRepo commented on sllm/serve/routers/roundrobin_router.py
> +        instance_id = await instance_allocation
Sure, it seems not possible for one instance to do multiple fine-tuning tasks. I can set a `fine_tuning_queue`, separate from `request_queue`. And add logic in `_load_balancer_loop` to limit each instance to running only one fine-tuning task at a time. I'm not sure if I'm understanding this correctly, so please correct me if I'm wrong somewhere.

2025-02-17 10:31 UTC, future-xy commented
> I've checked the current logic. In general, it's quite good but I still have some concerns about the router logic.
> 
> Currently, `fine_tuning` requests and `inference` requests will share the same scaling threshold in autoscaler (in line 265 of `roundrobin_router.py`) and same instance request length checking logic (in line 246). However, I think they should be somehow different. If it's inference request, let's keep the current logic in both autoscaling and routing. But if it's fine-tunning request, I think in any case, it should be one request occupy a whole instance, regardless of the config file. Or do you think it's fine if there are several finetunning tasks running on the same instance? How do you think @future-xy ?
> 
> Another point is currently one kind of model could only serve one kind of request. If there's inference requests in processing, fine-tune requests will be rejected. However, I don't think it should have a such hard limit. It would be fine if there's some inference instances processing inference tasks and some fine-tuning instances processing fine-tunning tasks. But considering it may be little bit tricky to do such a change, it's also fine if we keep the current logic and do the modification in future updates.

Good points! Thanks for sharing your thoughts.

1. Yes, let's process one fine-tuning request per time for now. We can revisit later if batching fine-tuning requests makes sense.
2. Let's keep the current logic for now. We can refine it in future PRs if needed.

Let me know if you have any other concerns!

2025-02-17 13:35 UTC, future-xy requested changes

2025-02-17 13:35 UTC, future-xy commented on sllm/serve/backends/backend_utils.py
> +    async def fine_tuning(self, request_data: Dict[str, Any]):
Keep this consistent with the other functions in the class.

2025-02-17 13:35 UTC, future-xy commented on tests/fine_tuning_test/failed_models.json
What is this file?

2025-02-17 13:35 UTC, future-xy commented on tests/fine_tuning_test/fine_tuning_test.py
an empty file?

2025-02-17 13:35 UTC, future-xy commented on tests/fine_tuning_test/supported_models.json
And what's this?

2025-02-17 13:35 UTC, future-xy commented on sllm_store/sllm_store/transformers.py
Please update the corresponding tests.

2025-02-17 16:32 UTC, MartinRepo commented on tests/fine_tuning_test/failed_models.json
sorry about that. `fine_tuning_test` folder has been deleted

2025-02-17 17:39 UTC, MartinRepo commented on sllm/serve/backends/backend_utils.py
> +    async def fine_tuning(self, request_data: Dict[str, Any]):
`fine_tuning` can only be supported by transformers backend. The vllm backend does not support it. This is why I didn't add `@abstractmethod` on it.

2025-02-18 02:56 UTC, SiyangShao commented on sllm/cli/fine_tuning.py
> +        self.base_model = args.base_model
Why not just use `logger.info(f"Start fine-tuning base model {config_data['model']})`? It seems that `config_data['modle']` is compulsory and it is same as `self.base_model`.

2025-02-18 10:49 UTC, MartinRepo commented on sllm/cli/fine_tuning.py
> +        self.base_model = args.base_model
Yes, I can directly use `config_data['model']`, just think it is a bit strange that using `sllm-cli fine-tuning` to directly fine-tuning model without specifying a model name explicitly.

I can use the similar method in `cli/deploy`. i.e. still receives the base model name parameter and adds it to config later. This will also make sure that it is the model that the user wants to fine tune. Like:
```
config_data = default_config
config_data["model"] = self.base_model
```
How do you think about it?

2025-02-18 11:02 UTC, MartinRepo commented on sllm/cli/fine_tuning.py
> +        self.base_model = args.base_model
I have updated the `--base_model` param process method. Now the value of `model` in `default_ft_config.json` has been removed. Users can still specify the base model name explicitly by `sllm-cli fine-tuning --base_model base_model_name`, then this model name will be updated into the config data.

2025-02-21 14:57 UTC, future-xy approved these changes
LGTM

2025-02-21 15:04 UTC, merged