[FEAT] Enhance deploy functionality to allow overriding default configuration
ServerlessLLM/ServerlessLLM pull request #32
Opened 2024-07-24 07:13 UTC by JustinTong0323

### Description

This PR improves the deploy functionality in `sllm-cli` by adding the flexibility to overwrite the default configuration parameters directly through the command line interface. Previously, the CLI only allowed deploying a model using the entire default configuration or a complete custom configuration. Now, users can specify individual configuration parameters to override the defaults.

### Changes

- Updated `DeployCommand` class in `deploy.py` to accept additional CLI arguments for overriding default configuration parameters:
  - `--backend`: Specify the backend to be used, overriding the default backend.
  - `--num_gpus`: Specify the required number of GPUs, overriding the default value.
  - `--target`: Specify the target concurrency, overriding the default value.
  - `--min_instances`: Specify the minimum instances for auto-scaling, overriding the default value.
  - `--max_instances`: Specify the maximum instances for auto-scaling, overriding the default value.

### Example Usage

Users can now deploy a model with specific configurations without needing a full custom configuration file. For instance:

```bash
sllm-cli deploy --model facebook/opt-1.3b --backend transformers --num_gpus 2 --target 2 --min_instances 1 --max_instances 5
```
In this example, the `facebook/opt-1.3b` model is deployed with the transformers backend, required 2 GPUs, a target concurrency of 2, minimum instances of 1, and maximum instances of 5.

2024-07-25 11:03 UTC, JustinTong0323 commented
This pr is related to #23 case 1.

2024-07-26 07:45 UTC, future-xy requested changes

2024-07-26 07:45 UTC, future-xy commented on serverless_llm/cli/deploy.py
> +            if self.backend is not None:
Verify the correctness. What if num_gpus = -1? 🤣

2024-07-29 05:20 UTC, future-xy requested changes

2024-07-29 05:20 UTC, future-xy commented on serverless_llm/cli/deploy.py
> +    def validate_args(self) -> None:
Call `validate config`. All requirements must be applied in one place to avoid potential inconsistency.

2024-07-29 10:36 UTC, future-xy approved these changes

2024-07-29 10:37 UTC, merged